binary_data_dir: data/binary/garbage
patch_size: 128
crop_size: 256
thresh_size: 128
test_crop_size: [ 2040, 2040 ]
test_thresh_size: 0
valid_steps: 4
num_sanity_val_steps: 4
eval_batch_size: 1
test_batch_size: 1
sr_scale: 4